// PassThrough {
//   _readableState: ReadableState {
//     objectMode: false,
//     highWaterMark: 33554432,
//     buffer: BufferList { head: null, tail: null, length: 0 },
//     length: 0,
//     pipes: [],
//     flowing: null,
//     ended: false,
//     endEmitted: false,
//     reading: false,
//     constructed: true,
//     sync: false,
//     needReadable: false,
//     emittedReadable: false,
//     readableListening: false,
//     resumeScheduled: false,
//     errorEmitted: false,
//     emitClose: true,
//     autoDestroy: true,
//     destroyed: false,
//     errored: null,
//     closed: false,
//     closeEmitted: false,
//     defaultEncoding: 'utf8',
//     awaitDrainWriters: null,
//     multiAwaitDrain: false,
//     readingMore: false,
//     dataEmitted: false,
//     decoder: null,
//     encoding: null,
//     [Symbol(kPaused)]: null
//   },
//   _events: [Object: null prototype] {
//     prefinish: [Function: prefinish],
//     error: [Function (anonymous)]
//   },
//   _eventsCount: 2,
//   _maxListeners: undefined,
//   _writableState: WritableState {
//     objectMode: false,
//     highWaterMark: 33554432,
//     finalCalled: false,
//     needDrain: false,
//     ending: false,
//     ended: false,
//     finished: false,
//     destroyed: false,
//     decodeStrings: true,
//     defaultEncoding: 'utf8',
//     length: 0,
//     writing: false,
//     corked: 0,
//     sync: true,
//     bufferProcessing: false,
//     onwrite: [Function: bound onwrite],
//     writecb: null,
//     writelen: 0,
//     afterWriteTickInfo: null,
//     buffered: [],
//     bufferedIndex: 0,
//     allBuffers: true,
//     allNoop: true,
//     pendingcb: 0,
//     constructed: true,
//     prefinished: false,
//     errorEmitted: false,
//     emitClose: true,
//     autoDestroy: true,
//     errored: null,
//     closed: false,
//     closeEmitted: false,
//     [Symbol(kOnFinished)]: []
//   },
//   allowHalfOpen: true,
//   _destroy: [Function (anonymous)],
//   [Symbol(kCapture)]: false,
//   [Symbol(kCallback)]: null
// }
// ---------------------
// PassThrough {
//   _readableState: ReadableState {
//     objectMode: false,
//     highWaterMark: 33554432,
//     buffer: BufferList { head: null, tail: null, length: 0 },
//     length: 0,
//     pipes: [],
//     flowing: null,
//     ended: false,
//     endEmitted: false,
//     reading: false,
//     constructed: true,
//     sync: false,
//     needReadable: false,
//     emittedReadable: false,
//     readableListening: false,
//     resumeScheduled: false,
//     errorEmitted: false,
//     emitClose: true,
//     autoDestroy: true,
//     destroyed: false,
//     errored: null,
//     closed: false,
//     closeEmitted: false,
//     defaultEncoding: 'utf8',
//     awaitDrainWriters: null,
//     multiAwaitDrain: false,
//     readingMore: false,
//     dataEmitted: false,
//     decoder: null,
//     encoding: null,
//     [Symbol(kPaused)]: null
//   },
//   _events: [Object: null prototype] {
//     prefinish: [Function: prefinish],
//     error: [Function (anonymous)]
//   },
//   _eventsCount: 2,
//   _maxListeners: undefined,
//   _writableState: WritableState {
//     objectMode: false,
//     highWaterMark: 33554432,
//     finalCalled: false,
//     needDrain: false,
//     ending: false,
//     ended: false,
//     finished: false,
//     destroyed: false,
//     decodeStrings: true,
//     defaultEncoding: 'utf8',
//     length: 0,
//     writing: false,
//     corked: 0,
//     sync: true,
//     bufferProcessing: false,
//     onwrite: [Function: bound onwrite],
//     writecb: null,
//     writelen: 0,
//     afterWriteTickInfo: null,
//     buffered: [],
//     bufferedIndex: 0,
//     allBuffers: true,
//     allNoop: true,
//     pendingcb: 0,
//     constructed: true,
//     prefinished: false,
//     errorEmitted: false,
//     emitClose: true,
//     autoDestroy: true,
//     errored: null,
//     closed: false,
//     closeEmitted: false,
//     [Symbol(kOnFinished)]: []
//   },
//   allowHalfOpen: true,
//   _destroy: [Function (anonymous)],
//   [Symbol(kCapture)]: false,
//   [Symbol(kCallback)]: null
// }